-- 043: LOCAL DRAFT, NOT APPLIED. Requires 001..038 and the private stays
-- boundary from 042. This migration deliberately refuses to run while a
-- browser role can read arbitrary stays or mutate them directly.
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'stays' AND c.relrowsecurity) THEN
    RAISE EXCEPTION 'APPLY_042_FIRST: stays RLS is not enabled';
  END IF;
  IF has_table_privilege('anon','public.stays','SELECT')
    OR has_any_column_privilege('anon','public.stays','SELECT')
    OR EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'stays'
      AND cmd = 'SELECT' AND roles && ARRAY['public','anon']::name[])
    OR has_table_privilege('authenticated','public.stays','INSERT,UPDATE,DELETE')
    OR has_any_column_privilege('authenticated','public.stays','INSERT,UPDATE')
    OR EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'stays'
      AND cmd IN ('INSERT','UPDATE','DELETE','ALL') AND roles && ARRAY['public','anon','authenticated']::name[])
    OR (SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename='stays'
      AND cmd='SELECT' AND roles && ARRAY['authenticated']::name[]) <> 1
    OR NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='stays'
      AND policyname='stays_private_own_read' AND cmd='SELECT' AND permissive='PERMISSIVE'
      AND roles = ARRAY['authenticated']::name[] AND with_check IS NULL
      AND regexp_replace(qual,'\s','','g') = '(user_id=(SELECTauth.uid()ASuid))')
  THEN
    RAISE EXCEPTION 'APPLY_042_FIRST: stays still has browser read/write access';
  END IF;
END $$;

ALTER TABLE public.stay_owner_leads
  ADD COLUMN IF NOT EXISTS applicant_user_id uuid REFERENCES public.users(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS publication_agreed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS publication_agreed_at timestamptz,
  ADD COLUMN IF NOT EXISTS publication_consent_version smallint,
  ADD COLUMN IF NOT EXISTS draft_confirmed_at timestamptz,
  ADD COLUMN IF NOT EXISTS draft_confirmed_stay_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_stay_owner_leads_applicant
  ON public.stay_owner_leads(applicant_user_id, created_at DESC)
  WHERE applicant_user_id IS NOT NULL;

DROP TRIGGER IF EXISTS update_stay_owner_leads_updated_at ON public.stay_owner_leads;
CREATE TRIGGER update_stay_owner_leads_updated_at BEFORE UPDATE ON public.stay_owner_leads
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.stay_workflow_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stay_id uuid REFERENCES public.stays(id) ON DELETE SET NULL,
  lead_id bigint REFERENCES public.stay_owner_leads(id) ON DELETE SET NULL,
  actor_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  action varchar(40) NOT NULL CHECK (action IN ('draft_created','owner_confirmed','admin_review')),
  before_state jsonb,
  after_state jsonb,
  note text CHECK (note IS NULL OR length(note) <= 1000),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stay_workflow_audit ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE item record;
BEGIN
  FOR item IN SELECT policyname FROM pg_policies
    WHERE schemaname='public' AND tablename='stay_workflow_audit'
  LOOP EXECUTE format('DROP POLICY %I ON public.stay_workflow_audit', item.policyname); END LOOP;
END $$;
REVOKE ALL PRIVILEGES ON public.stay_workflow_audit FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON public.stay_workflow_audit TO service_role;

CREATE OR REPLACE FUNCTION public.create_stay_owner_lead(p_applicant_user_id uuid, p_input jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_lead public.stay_owner_leads;
BEGIN
  IF p_applicant_user_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.users WHERE id = p_applicant_user_id) THEN
    RAISE EXCEPTION 'APPLICANT_NOT_FOUND';
  END IF;
  IF NOT (p_input ? 'name' AND p_input ? 'phone' AND p_input ? 'address')
    OR COALESCE((p_input->>'privacy_agreed')::boolean, false) IS NOT TRUE
    OR COALESCE((p_input->>'publication_agreed')::boolean, false) IS NOT TRUE THEN
    RAISE EXCEPTION 'CONSENT_REQUIRED';
  END IF;
  IF NOT (p_input - ARRAY['name','phone','address','building_name','unit_count','memo','source_code',
    'privacy_agreed','publication_agreed','marketing_agreed','detail','detail_version',
    'publication_consent_version']::text[] = '{}'::jsonb) THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_applicant_user_id::text, 43));
  IF (SELECT count(*) FROM public.stay_owner_leads WHERE applicant_user_id = p_applicant_user_id
      AND created_at >= date_trunc('day', timezone('utc', now())) AT TIME ZONE 'UTC') >= 5 THEN
    RAISE EXCEPTION 'RATE_LIMITED';
  END IF;
  INSERT INTO public.stay_owner_leads (applicant_user_id,name,phone,address,building_name,unit_count,memo,
    source_code,privacy_agreed,privacy_agreed_at,publication_agreed,publication_agreed_at,
    publication_consent_version,marketing_agreed,marketing_agreed_at,detail,detail_version,status,created_at,updated_at)
  VALUES (p_applicant_user_id,trim(p_input->>'name'),trim(p_input->>'phone'),trim(p_input->>'address'),
    nullif(trim(p_input->>'building_name'),''),(p_input->>'unit_count')::integer,nullif(trim(p_input->>'memo'),''),
    nullif(trim(p_input->>'source_code'),''),true,now(),true,now(),
    (p_input->>'publication_consent_version')::smallint,COALESCE((p_input->>'marketing_agreed')::boolean,false),
    CASE WHEN COALESCE((p_input->>'marketing_agreed')::boolean,false) THEN now() END,
    p_input->'detail',(p_input->>'detail_version')::smallint,'new',now(),now()) RETURNING * INTO v_lead;
  RETURN to_jsonb(v_lead);
END $$;
REVOKE ALL ON FUNCTION public.create_stay_owner_lead(uuid,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_stay_owner_lead(uuid,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.create_stay_owner_draft(p_lead_id bigint, p_admin_user_id uuid, p_stay jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_lead public.stay_owner_leads; v_stay public.stays; v_payload jsonb;
  allowed text[] := ARRAY['stay_type','deal_type','title','description','address','jibun_address','detail_address',
  'region','sigungu','lawd_cd','bcode','pnu','lat','lng','geocode_source','mgm_bldrgst_pk','building_name',
  'main_purps_cd_nm','use_apr_day','total_floors','elevator_cnt','parking_total','building_verified','floor',
  'exclusive_area','supply_area','rooms','baths','room_structure','max_guests','deposit_won','daily_fee_won',
  'weekly_fee_won','monthly_fee_won','maintenance_fee_won','maintenance_included','utilities_included',
  'min_stay_days','max_stay_days','available_from','available_to','amenities','appliances','parking_available',
  'pets_allowed','smoking_allowed','thumbnail','images','contact_name','phone','kakao_url','contact_hours','status','is_exclusive'];
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id=p_admin_user_id AND user_type='admin') THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
  SELECT * INTO v_lead FROM public.stay_owner_leads WHERE id=p_lead_id FOR UPDATE;
  IF NOT FOUND OR v_lead.applicant_user_id IS NULL OR v_lead.publication_agreed IS NOT TRUE THEN RAISE EXCEPTION 'LEAD_NOT_FOUND'; END IF;
  IF v_lead.converted_stay_id IS NOT NULL THEN RAISE EXCEPTION 'ALREADY_CONVERTED'; END IF;
  IF NOT (p_stay - allowed = '{}'::jsonb) THEN RAISE EXCEPTION 'INVALID_STAY_FIELDS'; END IF;
  v_payload := p_stay || jsonb_build_object('id',gen_random_uuid(),'user_id',v_lead.applicant_user_id,
    'owner_type','owner','source','owner_lead','lead_id',p_lead_id,'views',0,'is_active',true,'is_approved',false,
    'status',COALESCE(p_stay->>'status','available'),'is_exclusive',COALESCE((p_stay->>'is_exclusive')::boolean,false),
    'amenities',COALESCE(p_stay->'amenities','[]'::jsonb),'appliances',COALESCE(p_stay->'appliances','[]'::jsonb),
    'created_at',now(),'updated_at',now());
  INSERT INTO public.stays SELECT (jsonb_populate_record(NULL::public.stays,v_payload)).* RETURNING * INTO v_stay;
  UPDATE public.stay_owner_leads SET converted_stay_id=v_stay.id,status='converted',
    draft_confirmed_at=NULL,draft_confirmed_stay_updated_at=NULL WHERE id=p_lead_id;
  INSERT INTO public.stay_workflow_audit(stay_id,lead_id,actor_user_id,action,after_state)
    VALUES(v_stay.id,p_lead_id,p_admin_user_id,'draft_created',jsonb_build_object('updated_at',v_stay.updated_at));
  RETURN to_jsonb(v_stay);
END $$;
REVOKE ALL ON FUNCTION public.create_stay_owner_draft(bigint,uuid,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_stay_owner_draft(bigint,uuid,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.confirm_stay_owner_draft(p_lead_id bigint, p_applicant_user_id uuid,
  p_expected_stay_updated_at timestamptz)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_lead public.stay_owner_leads; v_stay public.stays; v_now timestamptz := now();
BEGIN
  SELECT * INTO v_lead FROM public.stay_owner_leads WHERE id=p_lead_id
    AND applicant_user_id=p_applicant_user_id FOR UPDATE;
  IF NOT FOUND OR v_lead.converted_stay_id IS NULL THEN RAISE EXCEPTION 'DRAFT_NOT_FOUND'; END IF;
  SELECT * INTO v_stay FROM public.stays WHERE id=v_lead.converted_stay_id AND user_id=p_applicant_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'DRAFT_NOT_FOUND'; END IF;
  IF v_stay.updated_at IS DISTINCT FROM p_expected_stay_updated_at THEN RAISE EXCEPTION 'DRAFT_CHANGED'; END IF;
  UPDATE public.stay_owner_leads SET draft_confirmed_at=v_now,
    draft_confirmed_stay_updated_at=v_stay.updated_at WHERE id=p_lead_id;
  INSERT INTO public.stay_workflow_audit(stay_id,lead_id,actor_user_id,action,after_state)
    VALUES(v_stay.id,p_lead_id,p_applicant_user_id,'owner_confirmed',jsonb_build_object('updated_at',v_stay.updated_at));
  RETURN jsonb_build_object('lead_id',p_lead_id,'confirmation',jsonb_build_object(
    'confirmed_at',v_now,'stay_updated_at',v_stay.updated_at,'is_current',true));
END $$;
REVOKE ALL ON FUNCTION public.confirm_stay_owner_draft(bigint,uuid,timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_stay_owner_draft(bigint,uuid,timestamptz) TO service_role;

CREATE OR REPLACE FUNCTION public.review_stay(p_stay_id uuid,p_admin_user_id uuid,p_patch jsonb,p_note text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_stay public.stays; v_after public.stays; v_lead public.stay_owner_leads; v_before jsonb;
  v_source varchar(20); v_lead_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id=p_admin_user_id AND user_type='admin') THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
  IF p_note IS NOT NULL AND length(p_note)>1000 THEN RAISE EXCEPTION 'NOTE_TOO_LONG'; END IF;
  IF p_patch = '{}'::jsonb OR NOT (p_patch - ARRAY['is_approved','is_active','status']::text[] = '{}'::jsonb) THEN RAISE EXCEPTION 'INVALID_PATCH'; END IF;
  SELECT source,lead_id INTO v_source,v_lead_id FROM public.stays WHERE id=p_stay_id;
  IF NOT FOUND THEN RETURN NULL; END IF;
  -- Delegated paths always lock lead then stay, matching confirmation/conversion.
  IF v_source='owner_lead' THEN
    SELECT * INTO v_lead FROM public.stay_owner_leads WHERE id=v_lead_id FOR UPDATE;
  END IF;
  SELECT * INTO v_stay FROM public.stays WHERE id=p_stay_id FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_stay.source IS DISTINCT FROM v_source OR v_stay.lead_id IS DISTINCT FROM v_lead_id THEN RAISE EXCEPTION 'DRAFT_CHANGED'; END IF;
  IF COALESCE((p_patch->>'is_approved')::boolean,false) IS TRUE AND v_stay.source='owner_lead' THEN
    IF v_lead.id IS NULL OR v_lead.privacy_agreed IS NOT TRUE OR v_lead.publication_agreed IS NOT TRUE
      OR v_lead.applicant_user_id IS DISTINCT FROM v_stay.user_id
      OR v_lead.converted_stay_id IS DISTINCT FROM v_stay.id
      OR v_lead.draft_confirmed_stay_updated_at IS NULL THEN RAISE EXCEPTION 'OWNER_CONFIRMATION_REQUIRED'; END IF;
    IF v_lead.draft_confirmed_stay_updated_at IS DISTINCT FROM v_stay.updated_at THEN RAISE EXCEPTION 'DRAFT_CHANGED'; END IF;
  END IF;
  v_before := jsonb_build_object('is_approved',v_stay.is_approved,'is_active',v_stay.is_active,'status',v_stay.status,'updated_at',v_stay.updated_at);
  UPDATE public.stays SET
    is_approved=CASE WHEN p_patch ? 'is_approved' THEN (p_patch->>'is_approved')::boolean ELSE is_approved END,
    is_active=CASE WHEN p_patch ? 'is_active' THEN (p_patch->>'is_active')::boolean ELSE is_active END,
    status=CASE WHEN p_patch ? 'status' THEN p_patch->>'status' ELSE status END
    WHERE id=p_stay_id RETURNING * INTO v_after;
  INSERT INTO public.stay_workflow_audit(stay_id,lead_id,actor_user_id,action,before_state,after_state,note)
    VALUES(v_after.id,v_after.lead_id,p_admin_user_id,'admin_review',v_before,
      jsonb_build_object('is_approved',v_after.is_approved,'is_active',v_after.is_active,'status',v_after.status,'updated_at',v_after.updated_at),p_note);
  RETURN to_jsonb(v_after);
END $$;
REVOKE ALL ON FUNCTION public.review_stay(uuid,uuid,jsonb,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.review_stay(uuid,uuid,jsonb,text) TO service_role;

COMMIT;
